// <auto-generated />
using System;
using ApiPessoa.Repositorio.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiPessoa.Repositorio.Migrations
{
    [DbContext(typeof(ApiPessoaContexto))]
    [Migration("20190905204902_inicio")]
    partial class inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("apipessoa")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiPessoa.Dominio.Pessoas.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PESSOA");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnName("TX_CPF");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("DT_NASCIMENTO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NM_NOME");

                    b.Property<int>("Sexo")
                        .HasColumnName("CD_SEXO");

                    b.HasKey("Id");

                    b.ToTable("PESSOA");
                });
#pragma warning restore 612, 618
        }
    }
}
